dataset: "ESD"

path:
  corpus_path: "/home/ispl/바탕화면/TTS/spk_151_dataset"
  lexicon_path: "/home/matt/DB/[BEN]multi_lingual/english_lexicon.txt"
  raw_path: "/home/ispl/바탕화면/TTS/BEN_TTS_toolkit/data_mspk75"
  preprocessed_path: "/home/lee/Desktop/INSUNG/intensity_fs2/ESD_preprocess_vocs_1/"
  alignment_path: "/home/lee/Desktop/INSUNG/intensity_fs2/ESD_preprocess_vocs_1/TextGrid/"
  stats_path: "/home/lee/Desktop/INSUNG/intensity_fs2/ESD_preprocess_vocs_1/stats.json"
  symbol_path: "/home/lee/Desktop/INSUNG/intensity_fs2/ESD_preprocess_vocs_1/symbols.json"

preprocessing:
  val_size: 512 #4
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 24000
    max_wav_value: 32768.0
  stft:
    filter_length: 2048
    hop_length: 300
    win_length: 1200
  mel:
    n_mel_channels: 80
    mel_fmin: 80
    mel_fmax: 7600
    normalization: True
  pitch:
    feature: "phoneme_level"
    normalization: True
    f0_max: 400.0
  energy:
    feature: "phoneme_level"
    normalization: True