dataset: "emo_intensity"

path:
  corpus_path: "/home/insung/PycharmProjects/Mixed_Emotions/ESD/"
#  lexicon_path: "/home/matt/DB/[BEN]multi_lingual/english_lexicon.txt"
  raw_path: "/home/insung/PycharmProjects/Mixed_Emotions/ESD/ESD_24_EN/"
  preprocessed_path: "/home/insung/PycharmProjects/Mixed_Emotions/emo_intensity/preprocess_intensity_300/"
  alignment_path: "/home/insung/PycharmProjects/Mixed_Emotions/ESD/ESD_24_EN_preprocess_300/TextGrid/"
#  stats_path: "/home/insung/PycharmProjects/pythonProject/spk_151_dataset/preprocessed/stats.json"
#  symbol_path: "/home/insung/PycharmProjects/pythonProject/spk_151_dataset/preprocessed/symbols.json"

preprocessing:
  val_size: 512 #4
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 24000
    max_wav_value: 32768.0
  stft:
    filter_length: 2048
    hop_length: 300
    win_length: 1200
  mel:
    n_mel_channels: 80
    mel_fmin: 80
    mel_fmax: 7600
    normalization: True
  pitch:
    feature: "phoneme_level"
    normalization: True
    f0_max: 400.0
  energy:
    feature: "phoneme_level"
    normalization: True